{
 "title": "Sample Namespace Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "pod_ip",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"}, pod_ip)"
   },
   {
    "name": "traefik_backend",
    "label": "Traefik Backend",
    "query": "label_values(traefik_backend_server_up{url=~\"http://(${pod_ip:pipe}):.*\"}, backend)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"})",
     "legendFormat": "{{deployment}} available"
    }
   ]
  },
  {
   "title": "Namespace CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", image!=\"\", pod_name=~\"$pod\", container_name!=\"POD\"}[1m]))",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_open_connections{backend=~\"$traefik_backend\"}) by (backend)",
     "legendFormat": "{{backend}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{namespace=~\"$namespace\"}[5m])) by (service)",
     "legendFormat": "Service: {{service}}"
    }
   ]
  },
  {
   "title": "Pods Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 14, "w": 3, "x": 0, "y": 8 } },
  {
   "title": "Namespace Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\", container_name!=\"POD\", container_name!=\"\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(container_memory_cache{job=\"kubelet\", namespace=\"$namespace\", container_name!=\"POD\", container_name!=\"\"})",
     "legendFormat": "Cache"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"$traefik_backend\", code=~\"(4)..\"}[5m])) by (backend, code)",
     "legendFormat": "{{backend}} 4xx"
    },
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"$traefik_backend\", code=~\"(5)..\"}[5m])) by (backend, code)",
     "legendFormat": "{{backend}} 5xx"
    },
    {
     "expr": "sum(rate(http_requests_received_total{namespace=~\"$namespace\", code=~\"(4)..\"}[5m])) by (service, code)",
     "legendFormat": "Service: {{service}} 4xx"
    },
    {
     "expr": "sum(rate(http_requests_received_total{namespace=~\"$namespace\", code=~\"(5)..\"}[5m])) by (service, code)",
     "legendFormat": "Service: {{service}} 5xx"
    }
   ]
  },
  {
   "title": "Namespace Network I/O",
   "type": "graph",
   "description": "Aggregated network input/output for all pods within the namespace.",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"kubelet\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{backend=~\"$traefik_backend\"}[5m])) by (backend) / sum(rate(traefik_backend_request_duration_seconds_count{backend=~\"$traefik_backend\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=~\"$namespace\"}[5m])) by (service) / sum(rate(http_request_duration_seconds_count{namespace=~\"$namespace\"}[5m])) by (service)",
     "legendFormat": "Service: {{service}}"
    }
   ]
  }
 ]
}