{
 "title": "Passenger Targets",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (rate(process_cpu_seconds_total{namespace=\"smartdata-ats-xaqxj\"}[1m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (process_resident_memory_bytes{namespace=\"smartdata-ats-xaqxj\"})",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (service) (up{namespace=\"smartdata-ats-xaqxj\"})",
     "legendFormat": "{{ service }}"
    }
   ]
  }
 ]
}