{
 "title": "Visual Recognition API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"terminal-unitnumberdet-enjmx\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "Virtual memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{namespace=\"terminal-unitnumberdet-enjmx\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "description": "1 if the API is live, 0 if it is down. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(up{namespace=\"terminal-unitnumberdet-enjmx\", service=\"visual-recognition-api\"})",
     "legendFormat": "API Uptime"
    }
   ]
  }
 ]
}