{
 "title": "Overdue Forecast",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Health Model API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of predicted invoices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "n_d365_predictions_total{service=\"overdueforecast-api\"}"
    },
    {
     "expr": "n_visma_predictions_total{service=\"overdueforecast-api\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"overdue-forecast-xryxn\", service=\"overdueforecast-api\"}[1m]))"
    },
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "Virtual memory usage of model-api REST API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{namespace=\"overdue-forecast-xryxn\",service=\"overdueforecast-api\"})"
    },
    {}
   ]
  },
  {
   "title": "Model API Uptime",
   "type": "state-timeline",
   "description": "1 if the API is live, 0 if it is down. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(up{namespace=\"overdue-forecast-xryxn\", service=\"overdueforecast-api\"})",
     "legendFormat": "Model API Uptime"
    }
   ]
  },
  { "title": "Monitoring of internal DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Number of invoices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  prediction_inserteddt AS \"time\",\r\n  count(invono) as \" D365 number of invoices\"\r\nFROM monitoring_view \r\nWHERE\r\n  $__timeFilter(prediction_inserteddt) and source_system='D365'\r\ngroup by prediction_inserteddt"
    },
    {
     "rawSql": "SELECT\r\n  prediction_inserteddt AS \"time\",\r\n  count(invono) as \" Visma number of invoices\"\r\nFROM monitoring_view \r\nWHERE\r\n  $__timeFilter(prediction_inserteddt) and source_system='Visma'\r\ngroup by prediction_inserteddt"
    }
   ]
  },
  {
   "title": "Probability overdue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  prediction_inserteddt AS \"time\",\r\n  avg(probability_overdue) as \"D365 probability overdue \"\r\nFROM monitoring_view \r\nWHERE\r\n  $__timeFilter(prediction_inserteddt) and source_system='D365'\r\ngroup by prediction_inserteddt"
    },
    {
     "rawSql": "SELECT\r\n  prediction_inserteddt AS \"time\",\r\n  avg(probability_overdue) as \"Visma probability overdue\"\r\nFROM monitoring_view \r\nWHERE\r\n  $__timeFilter(prediction_inserteddt) and source_system='Visma'\r\ngroup by prediction_inserteddt"
    }
   ]
  },
  {
   "title": "Percentage of null values in features",
   "type": "timeseries",
   "description": "Percentage of null values in features after encoding of features. It is a good indicator of feature drift",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  prediction_inserteddt AS \"time\",\r\n  avg(is_nan_in_features::int) as \"D365 nan in features\"\r\nFROM monitoring_view \r\nWHERE\r\n  $__timeFilter(prediction_inserteddt) and source_system='D365'\r\ngroup by prediction_inserteddt"
    },
    {
     "rawSql": "SELECT\r\n  prediction_inserteddt AS \"time\",\r\n  avg(is_nan_in_features::int) as \"Visma nan in features\"\r\nFROM monitoring_view \r\nWHERE\r\n  $__timeFilter(prediction_inserteddt) and source_system='Visma'\r\ngroup by prediction_inserteddt"
    }
   ]
  }
 ]
}