{
 "title": "FOCD",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Average daily collections in minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "focd_average_daily_collections_sum{namespace=\"logistics-forecasting-bnqag\"}>0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number of predictions over last month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(focd_n_predictions_total{namespace=\"logistics-forecasting-bnqag\"}[31d])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Failures over last 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(focd_n_failures_total{namespace=\"logistics-forecasting-bnqag\"}[24h])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Response time production",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "focd_response_time_seconds_bucket{namespace=\"logistics-forecasting-bnqag\", service=\"focd-model-api-production\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}