{
 "title": "Freight overbooking",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up time",
   "type": "state-timeline",
   "description": "Boolean returning 0 if down and 1 if up ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"})",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Times generated",
   "type": "stat",
   "description": "Shows the number of times that the model has been asked for predictions",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(n_times_generated_total{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"})"
    }
   ]
  },
  {
   "title": "Number of predictions generated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "n_row_times_generated_total{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"}"
    }
   ]
  },
  {
   "title": "Predictions",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "OB_predictions_bucket", "legendFormat": "{{le}}" }
   ]
  }
 ]
}