{
 "title": "optimization tasks",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Failures per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(num_optimize_failures_total{service=\"cargoallocation-app-production\", namespace=\"terminal-cargoallocati-zamrl\"}[1d]))"
    }
   ]
  },
  {
   "title": "Number of units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (vessel_id) (increase(num_units{}[$__rate_interval]))",
     "legendFormat": "{{vessel_id}}"
    }
   ]
  },
  {
   "title": "Excecution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (task,vessel_id) (increase(optimizer_task_duration{}[$__rate_interval]))",
     "legendFormat": "{{task}}-{{vessel_id}}"
    }
   ]
  },
  {
   "title": "Optimizations tasks started over a year",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (vessel_id) (increase(num_optimize_tasks_total{service=\"cargoallocation-app-production\", namespace=\"terminal-cargoallocati-zamrl\"}[1y]))",
     "legendFormat": "{{vessel_id}}"
    }
   ]
  }
 ]
}