{
 "title": "Logistics Quote Tenders",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Quote Tender Prod uptime",
   "type": "timeseries",
   "description": "If both backend and frontend are healthy, the value should be 2. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{namespace=\"logistics-quotes-eqxam\",service=~\"quote-tenders|quote-tenders-backend\"}"
    }
   ]
  },
  {
   "title": "Quote Tender Staging uptime",
   "type": "timeseries",
   "description": "If both backend and frontend are healthy, the value should be 2. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{namespace=\"logistics-quote-stagin-zlpxz\",service=~\"quote-tenders|quote-tenders-backend\"}"
    }
   ]
  },
  {
   "title": "Number of quotes calculated with tender tool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "n_indiviual_quotes_total{namespace=\"logistics-quotes-eqxam\",service=\"quote-tenders-backend\"}"
    }
   ]
  },
  {
   "title": "Number of distance calculations with tender tool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "n_individual_distances_total{namespace=\"logistics-quotes-eqxam\"}"
    }
   ]
  },
  {
   "title": "Request counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "flask_http_request_total{namespace=\"logistics-quotes-eqxam\", service=\"quote-tenders\"}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{}"
    }
   ]
  }
 ]
}