{
 "title": "Selfservice",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Apps running",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(up{namespace=\"selfservice\"}) by (service) - sum(up{namespace=\"selfservice\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"build.dfds.cloud\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{namespace=~\"selfservice\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Apps running timeseries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Status" }
   ],
   "targets": [
    {
     "expr": "count(up{namespace=\"selfservice\"}) by (service) - sum(up{namespace=\"selfservice\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Failed request rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Error request rate" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\",backend=~\"build.dfds.cloud\"}[5m])) by (backend)",
     "legendFormat": "{{backend}} 5XX"
    },
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"4..\",backend=~\"build.dfds.cloud\"}[5m])) by (backend)",
     "legendFormat": "{{backend}} 4XX"
    },
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"5..\",namespace=~\"selfservice\"}[5m])) by (service)",
     "legendFormat": "{{service}} 5XX"
    },
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"4..\",namespace=~\"selfservice\"}[5m])) by (service)",
     "legendFormat": "{{service}} 4XX"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "graph",
   "description": "Consumer group lag of build.capabilities kafka topic",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    {
     "format": "short",
     "label": "Consumer lag (negative values => zero)"
    }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"build.capabilities\",consumergroup!=\"\",consumergroup!=\"iam-role-service-consumer\",consumergroup!=\"argojanitor-consumer-production\"}) by (topic,consumergroup)",
     "legendFormat": "{{topic}}:{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "Request duration [s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{backend=~\"build.dfds.cloud\"}[5m])) by (backend) / sum(rate(traefik_backend_request_duration_seconds_count{backend=~\"build.dfds.cloud\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=~\"selfservice\"}[5m])) by (service) / sum(rate(http_request_duration_seconds_count{namespace=~\"selfservice\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Messages in per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Meesages in / min" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=~\"build.capabilities\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}